
### CloudFormation automatiser l'installation de notre infrastructure sur AWS ###

### Nos services sont dans la Zone de disponibilité AWS Europe(Paris):eu-west-3 ###

#################################
### Infrastructure du système ###
#################################

## Création solution Amazon S3
oc-projet10-lionel-bellerose:
    Type: AWS::S3::Bucket

    ######################################

## Création de la base de données MariaDB
Wordpress_DB:
  Type: AWS::RDS::DBInstance
  Properties:
    AllocatedStorage: '20'
    DBInstanceClass: db.t2.micro
    AvailabilityZone: eu-west-3a
    Engine: MariaDB
    DBName: wordpress
    MasterUsername: Admin
    MasterUserPassword: admin
    MultiAZ: 'true'
  DeletionPolicy: Snapshot

## Création du sécurityGroup
  DB_security:
  Type: AWS::RDS::DBSecurityGroup
  Properties:
    DBSecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: '3306'
      ToPort: '3306'
      CidrIp: 10.0.0.0/16

      #########################################


 